services:
  web:
    image: nginx:alpine
    networks:
      - my_private_network
    ports:
      - "8086:80"

  client:
    image: alpine
    command: tail -f /dev/null # Lệnh này giúp container không bị tắt ngay sau khi chạy
    networks:
      - my_private_network

networks:
  my_private_network:
    driver: bridge
