# Sử dụng nginx:latest làm base image
FROM nginx:latest

# Sao chép file index.html vào thư mục phục vụ web mặc định của Nginx
COPY index.html /usr/share/nginx/html/index.html

# Mở cổng 80 (cổng mặc định của Nginx)
EXPOSE 80
